# Generated by Django 3.2.12 on 2024-01-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_stripe_product_price_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='basket',
            name='session_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
